ERROR - 2023-03-07 05:45:39 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('103.76.120.90', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(18): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->index()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(18): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->index()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-07 05:45:39 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Logdata.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Logdata->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-07 05:45:42 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('103.76.120.90', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(18): CodeIgniter\BaseModel->findAll()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->index()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
#5 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(18): CodeIgniter\BaseModel->findAll()
#6 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->index()
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2023-03-07 05:45:42 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `logdata`
ORDER BY `id` DESC', [], false)
 3 SYSTEMPATH\Model.php(241): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(618): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Logdata.php(18): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Logdata->index()
 7 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
 8 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
ERROR - 2023-03-07 05:46:20 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('103.76.120.90', 'phpmyadmin', 'Cloudhost12345', 'db_kel7', 3306, '', 0)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#3 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#4 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#5 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#6 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#7 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#10 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in E:\xampp\htdocs\logdata1\logdata\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
#2 E:\xampp\htdocs\logdata1\logdata\system\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `lo...', Array, false)
#3 E:\xampp\htdocs\logdata1\logdata\system\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
#4 E:\xampp\htdocs\logdata1\logdata\system\BaseModel.php(782): CodeIgniter\Model->doInsert(Array)
#5 E:\xampp\htdocs\logdata1\logdata\system\Model.php(730): CodeIgniter\BaseModel->insert(Array, true)
#6 E:\xampp\htdocs\logdata1\logdata\app\Controllers\Logdata.php(43): CodeIgniter\Model->insert(Array)
#7 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(934): App\Controllers\Logdata->create()
#8 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
#9 E:\xampp\htdocs\logdata1\logdata\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 E:\xampp\htdocs\logdata1\logdata\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 E:\xampp\htdocs\logdata1\logdata\system\Commands\Server\rewrite.php(47): require_once('E:\\xampp\\htdocs...')
#12 {main}
CRITICAL - 2023-03-07 05:46:20 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(573): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2309): CodeIgniter\Database\BaseConnection->query('INSERT INTO `logdata` (`suhu`, `kelembapan`, `blok`) VALUES (:suhu:, :kelembapan:, :blok:)', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(782): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(730): CodeIgniter\BaseModel->insert([...], true)
 6 APPPATH\Controllers\Logdata.php(43): CodeIgniter\Model->insert([...])
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Logdata->create()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Logdata))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('FCPATH\\index.php')
